### ISSUE TITLE
Tests are flapping

### ISSUE THREAD

**Issue by AlexDaniel** [frithnanth/perl6-Math-FFT-Libfftw3#1] opened 2019-10-20 14:30 UTC
See this comment: https://github.com/rakudo/rakudo/issues/3237#issuecomment-544241679

**Comment by frithnanth** [comment] 2019-10-20 15:22
All the CArray I use are assigned to attributes, so I suppose they last until the object itself lasts.
Though the one thing I can suspect is that in order to avoid copying data, I just bind, this way:
```perl6
method somemethod()
{
…
@!out := CArray[num64].new: 0e0 xx @!in.list.elems;
…
}
```
Might this be the origin of the problem?

**Comment by frithnanth** [comment] 2019-10-27 18:41
I am not able to reproduce the issue, probably because I'm using v. 2019.07.1, but I'm keeping this issue open until the next version of Rakudo is out.

**Comment by frithnanth** [comment] 2019-12-03 08:37
The present version of this modules passes all its tests using v.2019.11, even when executed with `rakudo-valgrind-m`.

**Closed as completed by frithnanth** 2019-12-03 08:37 UTC
